spring:
  profiles:
    active: prod
  jackson:
    default-property-inclusion: non_null


jwt:
  secret: ah9823hrwbe1ytehwbfidsbr34hrj3
  expires: 172800000


knife4j:
  enable: true
  setting:
    language: zh_cn
    # 配置账号密码访问文档
  basic:
    enable: true
    username: admin
    password: 123456


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleteStatus
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl


logPath: logs
logName: hp
logBusinessLevel: debug
logRootLevel: info
logging:
  config: classpath:logback-spring.xml