-- ----------------------------
-- Table structure for sys_menu_perm
-- ----------------------------
DROP TABLE IF EXISTS `sys_menu_perm`;
CREATE TABLE `sys_menu_perm`
(
    `menu_id` bigint DEFAULT NULL COMMENT '菜单主键ID',
    `perm_id` bigint DEFAULT NULL COMMENT '权限主键ID'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='菜单-权限';

INSERT INTO `sys_menu_perm`
VALUES ('3', '1');
INSERT INTO `sys_menu_perm`
VALUES ('3', '2');
INSERT INTO `sys_menu_perm`
VALUES ('5', '1');
INSERT INTO `sys_menu_perm`
VALUES ('5', '2');
INSERT INTO `sys_menu_perm`
VALUES ('9', '1');
INSERT INTO `sys_menu_perm`
VALUES ('9', '2');
INSERT INTO `sys_menu_perm`
VALUES ('10', '1');
INSERT INTO `sys_menu_perm`
VALUES ('10', '2');
INSERT INTO `sys_menu_perm`
VALUES ('11', '1');
INSERT INTO `sys_menu_perm`
VALUES ('11', '2');
INSERT INTO `sys_menu_perm`
VALUES ('12', '1');
INSERT INTO `sys_menu_perm`
VALUES ('12', '2');
INSERT INTO `sys_menu_perm`
VALUES ('13', '1');
INSERT INTO `sys_menu_perm`
VALUES ('13', '2');
INSERT INTO `sys_menu_perm`
VALUES ('16', '1');
INSERT INTO `sys_menu_perm`
VALUES ('16', '2');
INSERT INTO `sys_menu_perm`
VALUES ('17', '1');
INSERT INTO `sys_menu_perm`
VALUES ('17', '2');
INSERT INTO `sys_menu_perm`
VALUES ('18', '1');
INSERT INTO `sys_menu_perm`
VALUES ('18', '2');
INSERT INTO `sys_menu_perm`
VALUES ('19', '1');
INSERT INTO `sys_menu_perm`
VALUES ('19', '2');
INSERT INTO `sys_menu_perm`
VALUES ('21', '1');
INSERT INTO `sys_menu_perm`
VALUES ('21', '2');
INSERT INTO `sys_menu_perm`
VALUES ('22', '1');
INSERT INTO `sys_menu_perm`
VALUES ('22', '2');
INSERT INTO `sys_menu_perm`
VALUES ('23', '1');
INSERT INTO `sys_menu_perm`
VALUES ('23', '2');
INSERT INTO `sys_menu_perm`
VALUES ('24', '1');
INSERT INTO `sys_menu_perm`
VALUES ('24', '2');
INSERT INTO `sys_menu_perm`
VALUES ('25', '1');
INSERT INTO `sys_menu_perm`
VALUES ('25', '2');
INSERT INTO `sys_menu_perm`
VALUES ('28', '1');
INSERT INTO `sys_menu_perm`
VALUES ('28', '2');
INSERT INTO `sys_menu_perm`
VALUES ('29', '1');
INSERT INTO `sys_menu_perm`
VALUES ('29', '2');
INSERT INTO `sys_menu_perm`
VALUES ('30', '1');
INSERT INTO `sys_menu_perm`
VALUES ('30', '2');
INSERT INTO `sys_menu_perm`
VALUES ('31', '1');
INSERT INTO `sys_menu_perm`
VALUES ('31', '2');
INSERT INTO `sys_menu_perm`
VALUES ('33', '1');
INSERT INTO `sys_menu_perm`
VALUES ('33', '2');
INSERT INTO `sys_menu_perm`
VALUES ('34', '1');
INSERT INTO `sys_menu_perm`
VALUES ('34', '2');
INSERT INTO `sys_menu_perm`
VALUES ('35', '1');
INSERT INTO `sys_menu_perm`
VALUES ('35', '2');
INSERT INTO `sys_menu_perm`
VALUES ('36', '1');
INSERT INTO `sys_menu_perm`
VALUES ('36', '2');
INSERT INTO `sys_menu_perm`
VALUES ('37', '1');
INSERT INTO `sys_menu_perm`
VALUES ('37', '2');
INSERT INTO `sys_menu_perm`
VALUES ('41', '1');
INSERT INTO `sys_menu_perm`
VALUES ('41', '2');
INSERT INTO `sys_menu_perm`
VALUES ('43', '1');
INSERT INTO `sys_menu_perm`
VALUES ('43', '2');
INSERT INTO `sys_menu_perm`
VALUES ('44', '1');
INSERT INTO `sys_menu_perm`
VALUES ('44', '2');
INSERT INTO `sys_menu_perm`
VALUES ('48', '1');
INSERT INTO `sys_menu_perm`
VALUES ('48', '2');
INSERT INTO `sys_menu_perm`
VALUES ('49', '1');
INSERT INTO `sys_menu_perm`
VALUES ('49', '2');
INSERT INTO `sys_menu_perm`
VALUES ('50', '1');
INSERT INTO `sys_menu_perm`
VALUES ('50', '2');
INSERT INTO `sys_menu_perm`
VALUES ('51', '1');
INSERT INTO `sys_menu_perm`
VALUES ('52', '1');
INSERT INTO `sys_menu_perm`
VALUES ('53', '1');
INSERT INTO `sys_menu_perm`
VALUES ('47', '1');
INSERT INTO `sys_menu_perm`
VALUES ('47', '2');
INSERT INTO `sys_menu_perm`
VALUES ('54', '1');
INSERT INTO `sys_menu_perm`
VALUES ('54', '2');
INSERT INTO `sys_menu_perm`
VALUES ('67', '1');
INSERT INTO `sys_menu_perm`
VALUES ('67', '28');
INSERT INTO `sys_menu_perm`
VALUES ('67', '29');
INSERT INTO `sys_menu_perm`
VALUES ('67', '30');
INSERT INTO `sys_menu_perm`
VALUES ('67', '31');
INSERT INTO `sys_menu_perm`
VALUES ('67', '32');
INSERT INTO `sys_menu_perm`
VALUES ('82', '1');
INSERT INTO `sys_menu_perm`
VALUES ('82', '2');
INSERT INTO `sys_menu_perm`
VALUES ('81', '1');
INSERT INTO `sys_menu_perm`
VALUES ('81', '2');
INSERT INTO `sys_menu_perm`
VALUES ('80', '1');
INSERT INTO `sys_menu_perm`
VALUES ('80', '2');
INSERT INTO `sys_menu_perm`
VALUES ('79', '1');
INSERT INTO `sys_menu_perm`
VALUES ('79', '2');
INSERT INTO `sys_menu_perm`
VALUES ('78', '1');
INSERT INTO `sys_menu_perm`
VALUES ('78', '2');
INSERT INTO `sys_menu_perm`
VALUES ('88', '1');
INSERT INTO `sys_menu_perm`
VALUES ('87', '1');
INSERT INTO `sys_menu_perm`
VALUES ('86', '1');
INSERT INTO `sys_menu_perm`
VALUES ('85', '1');
INSERT INTO `sys_menu_perm`
VALUES ('103', '1');
INSERT INTO `sys_menu_perm`
VALUES ('102', '1');
INSERT INTO `sys_menu_perm`
VALUES ('101', '1');
INSERT INTO `sys_menu_perm`
VALUES ('100', '1');
INSERT INTO `sys_menu_perm`
VALUES ('99', '1');
INSERT INTO `sys_menu_perm`
VALUES ('104', '1');
INSERT INTO `sys_menu_perm`
VALUES ('7', '1');
INSERT INTO `sys_menu_perm`
VALUES ('112', '1');
INSERT INTO `sys_menu_perm`
VALUES ('111', '1');
INSERT INTO `sys_menu_perm`
VALUES ('110', '1');
INSERT INTO `sys_menu_perm`
VALUES ('109', '1');
INSERT INTO `sys_menu_perm`
VALUES ('108', '1');
INSERT INTO `sys_menu_perm`
VALUES ('119', '1');
INSERT INTO `sys_menu_perm`
VALUES ('118', '1');
INSERT INTO `sys_menu_perm`
VALUES ('117', '1');
INSERT INTO `sys_menu_perm`
VALUES ('116', '1');
INSERT INTO `sys_menu_perm`
VALUES ('115', '1');
INSERT INTO `sys_menu_perm`
VALUES ('120', '1');
INSERT INTO `sys_menu_perm`
VALUES ('121', '1');
INSERT INTO `sys_menu_perm`
VALUES ('122', '1');
INSERT INTO `sys_menu_perm`
VALUES ('124', '1');
INSERT INTO `sys_menu_perm`
VALUES ('125', '1');
INSERT INTO `sys_menu_perm`
VALUES ('133', '1');
INSERT INTO `sys_menu_perm`
VALUES ('132', '1');
INSERT INTO `sys_menu_perm`
VALUES ('131', '1');
INSERT INTO `sys_menu_perm`
VALUES ('130', '1');
INSERT INTO `sys_menu_perm`
VALUES ('129', '1');
INSERT INTO `sys_menu_perm`
VALUES ('128', '1');
INSERT INTO `sys_menu_perm`
VALUES ('134', '1');
INSERT INTO `sys_menu_perm`
VALUES ('141', '1');
INSERT INTO `sys_menu_perm`
VALUES ('138', '1');
INSERT INTO `sys_menu_perm`
VALUES ('139', '1');
INSERT INTO `sys_menu_perm`
VALUES ('140', '1');
INSERT INTO `sys_menu_perm`
VALUES ('137', '1');
INSERT INTO `sys_menu_perm`
VALUES ('142', '1');
INSERT INTO `sys_menu_perm`
VALUES ('143', '1');
INSERT INTO `sys_menu_perm`
VALUES ('144', '1');
INSERT INTO `sys_menu_perm`
VALUES ('147', '1');
INSERT INTO `sys_menu_perm`
VALUES ('148', '1');
INSERT INTO `sys_menu_perm`
VALUES ('149', '1');
INSERT INTO `sys_menu_perm`
VALUES ('150', '1');
INSERT INTO `sys_menu_perm`
VALUES ('151', '1');
INSERT INTO `sys_menu_perm`
VALUES ('152', '1');
INSERT INTO `sys_menu_perm`
VALUES ('153', '1');
INSERT INTO `sys_menu_perm`
VALUES ('157', '1');
INSERT INTO `sys_menu_perm`
VALUES ('164', '1');
INSERT INTO `sys_menu_perm`
VALUES ('160', '1');
INSERT INTO `sys_menu_perm`
VALUES ('161', '1');
INSERT INTO `sys_menu_perm`
VALUES ('162', '1');
INSERT INTO `sys_menu_perm`
VALUES ('163', '1');
INSERT INTO `sys_menu_perm`
VALUES ('165', '1');
INSERT INTO `sys_menu_perm`
VALUES ('166', '1');
INSERT INTO `sys_menu_perm`
VALUES ('167', '1');
INSERT INTO `sys_menu_perm`
VALUES ('174', '1');
INSERT INTO `sys_menu_perm`
VALUES ('170', '1');
INSERT INTO `sys_menu_perm`
VALUES ('171', '1');
INSERT INTO `sys_menu_perm`
VALUES ('172', '1');
INSERT INTO `sys_menu_perm`
VALUES ('173', '1');
INSERT INTO `sys_menu_perm`
VALUES ('177', '1');
INSERT INTO `sys_menu_perm`
VALUES ('178', '1');
INSERT INTO `sys_menu_perm`
VALUES ('179', '1');
INSERT INTO `sys_menu_perm`
VALUES ('180', '1');
INSERT INTO `sys_menu_perm`
VALUES ('181', '1');
INSERT INTO `sys_menu_perm`
VALUES ('182', '1');
INSERT INTO `sys_menu_perm`
VALUES ('207', '1');
INSERT INTO `sys_menu_perm`
VALUES ('208', '1');
INSERT INTO `sys_menu_perm`
VALUES ('202', '1');
INSERT INTO `sys_menu_perm`
VALUES ('204', '1');
INSERT INTO `sys_menu_perm`
VALUES ('205', '1');
INSERT INTO `sys_menu_perm`
VALUES ('206', '1');
INSERT INTO `sys_menu_perm`
VALUES ('210', '1');
INSERT INTO `sys_menu_perm`
VALUES ('211', '1');
INSERT INTO `sys_menu_perm`
VALUES ('212', '1');
INSERT INTO `sys_menu_perm`
VALUES ('213', '1');
INSERT INTO `sys_menu_perm`
VALUES ('214', '1');
INSERT INTO `sys_menu_perm`
VALUES ('89', '1');
INSERT INTO `sys_menu_perm`
VALUES ('75', '1');
INSERT INTO `sys_menu_perm`
VALUES ('74', '1');
INSERT INTO `sys_menu_perm`
VALUES ('73', '1');
INSERT INTO `sys_menu_perm`
VALUES ('203', '1');
INSERT INTO `sys_menu_perm`
VALUES ('38', '1');
INSERT INTO `sys_menu_perm`
VALUES ('38', '83');
INSERT INTO `sys_menu_perm`
VALUES ('38', '2');
INSERT INTO `sys_menu_perm`
VALUES ('217', '1');
INSERT INTO `sys_menu_perm`
VALUES ('218', '1');
INSERT INTO `sys_menu_perm`
VALUES ('219', '1');
INSERT INTO `sys_menu_perm`
VALUES ('221', '1');
INSERT INTO `sys_menu_perm`
VALUES ('220', '1');
INSERT INTO `sys_menu_perm`
VALUES ('222', '1');
INSERT INTO `sys_menu_perm`
VALUES ('224', '1');
INSERT INTO `sys_menu_perm`
VALUES ('225', '1');
INSERT INTO `sys_menu_perm`
VALUES ('226', '1');
INSERT INTO `sys_menu_perm`
VALUES ('227', '1');
INSERT INTO `sys_menu_perm`
VALUES ('228', '1');
INSERT INTO `sys_menu_perm`
VALUES ('229', '1');
INSERT INTO `sys_menu_perm`
VALUES ('231', '1');
INSERT INTO `sys_menu_perm`
VALUES ('232', '1');
INSERT INTO `sys_menu_perm`
VALUES ('233', '1');
INSERT INTO `sys_menu_perm`
VALUES ('234', '1');
INSERT INTO `sys_menu_perm`
VALUES ('235', '1');
INSERT INTO `sys_menu_perm`
VALUES ('236', '1');
INSERT INTO `sys_menu_perm`
VALUES ('237', '1');
INSERT INTO `sys_menu_perm`
VALUES ('238', '1');
INSERT INTO `sys_menu_perm`
VALUES ('239', '1');
INSERT INTO `sys_menu_perm`
VALUES ('240', '1');
INSERT INTO `sys_menu_perm`
VALUES ('241', '1');
INSERT INTO `sys_menu_perm`
VALUES ('242', '1');
INSERT INTO `sys_menu_perm`
VALUES ('243', '1');
INSERT INTO `sys_menu_perm`
VALUES ('244', '1');
INSERT INTO `sys_menu_perm`
VALUES ('245', '1');
INSERT INTO `sys_menu_perm`
VALUES ('246', '1');
INSERT INTO `sys_menu_perm`
VALUES ('247', '1');
INSERT INTO `sys_menu_perm`
VALUES ('248', '1');
INSERT INTO `sys_menu_perm`
VALUES ('249', '1');
INSERT INTO `sys_menu_perm`
VALUES ('250', '1');
INSERT INTO `sys_menu_perm`
VALUES ('251', '1');
INSERT INTO `sys_menu_perm`
VALUES ('252', '1');
INSERT INTO `sys_menu_perm`
VALUES ('253', '1');
INSERT INTO `sys_menu_perm`
VALUES ('254', '1');
INSERT INTO `sys_menu_perm`
VALUES ('255', '1');
INSERT INTO `sys_menu_perm`
VALUES ('256', '1');
INSERT INTO `sys_menu_perm`
VALUES ('259', '1');
INSERT INTO `sys_menu_perm`
VALUES ('185', '1');
INSERT INTO `sys_menu_perm`
VALUES ('56', '1');
INSERT INTO `sys_menu_perm`
VALUES ('56', '2');
INSERT INTO `sys_menu_perm`
VALUES ('59', '1');
INSERT INTO `sys_menu_perm`
VALUES ('59', '2');
INSERT INTO `sys_menu_perm`
VALUES ('55', '1');
INSERT INTO `sys_menu_perm`
VALUES ('55', '2');
INSERT INTO `sys_menu_perm`
VALUES ('4', '1');
INSERT INTO `sys_menu_perm`
VALUES ('4', '2');
INSERT INTO `sys_menu_perm`
VALUES ('6', '1');
INSERT INTO `sys_menu_perm`
VALUES ('60', '1');
INSERT INTO `sys_menu_perm`
VALUES ('60', '2');
INSERT INTO `sys_menu_perm`
VALUES ('57', '1');
INSERT INTO `sys_menu_perm`
VALUES ('57', '2');
INSERT INTO `sys_menu_perm`
VALUES ('61', '1');
INSERT INTO `sys_menu_perm`
VALUES ('61', '2');
INSERT INTO `sys_menu_perm`
VALUES ('58', '1');
INSERT INTO `sys_menu_perm`
VALUES ('58', '2');
INSERT INTO `sys_menu_perm`
VALUES ('45', '1');
INSERT INTO `sys_menu_perm`
VALUES ('45', '2');
INSERT INTO `sys_menu_perm`
VALUES ('40', '1');
INSERT INTO `sys_menu_perm`
VALUES ('40', '2');
INSERT INTO `sys_menu_perm`
VALUES ('42', '1');
INSERT INTO `sys_menu_perm`
VALUES ('42', '2');
INSERT INTO `sys_menu_perm`
VALUES ('184', '1');
INSERT INTO `sys_menu_perm`
VALUES ('72', '1');
INSERT INTO `sys_menu_perm`
VALUES ('71', '1');
